# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\qt_andor_setup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(794, 553)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Dialog.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxAcquisitionMode = QtWidgets.QComboBox(self.tab)
        self.comboBoxAcquisitionMode.setMinimumSize(QtCore.QSize(188, 0))
        self.comboBoxAcquisitionMode.setObjectName("comboBoxAcquisitionMode")
        self.verticalLayout.addWidget(self.comboBoxAcquisitionMode)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.comboBoxTriggerMode = QtWidgets.QComboBox(self.tab)
        self.comboBoxTriggerMode.setMinimumSize(QtCore.QSize(270, 0))
        self.comboBoxTriggerMode.setObjectName("comboBoxTriggerMode")
        self.verticalLayout_2.addWidget(self.comboBoxTriggerMode)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.comboBoxReadoutMode = QtWidgets.QComboBox(self.tab)
        self.comboBoxReadoutMode.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBoxReadoutMode.setObjectName("comboBoxReadoutMode")
        self.verticalLayout_3.addWidget(self.comboBoxReadoutMode)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_Exposure = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBox_Exposure.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_Exposure.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_Exposure.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_Exposure.setReadOnly(False)
        self.spinBox_Exposure.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_Exposure.setDecimals(6)
        self.spinBox_Exposure.setMinimum(0.0)
        self.spinBox_Exposure.setMaximum(300.0)
        self.spinBox_Exposure.setSingleStep(0.001)
        self.spinBox_Exposure.setProperty("value", 0.0035)
        self.spinBox_Exposure.setObjectName("spinBox_Exposure")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_Exposure)
        self.checkBoxBaselineClamping = QtWidgets.QCheckBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxBaselineClamping.sizePolicy().hasHeightForWidth())
        self.checkBoxBaselineClamping.setSizePolicy(sizePolicy)
        self.checkBoxBaselineClamping.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }")
        self.checkBoxBaselineClamping.setText("")
        self.checkBoxBaselineClamping.setObjectName("checkBoxBaselineClamping")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkBoxBaselineClamping)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 3, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBoxVS = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxVS.setObjectName("comboBoxVS")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxVS)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBoxVoltage = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxVoltage.setObjectName("comboBoxVoltage")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxVoltage)
        self.verticalLayout_6.addLayout(self.formLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBoxHSRate = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxHSRate.setObjectName("comboBoxHSRate")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxHSRate)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBoxPreAmpGain = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxPreAmpGain.setObjectName("comboBoxPreAmpGain")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxPreAmpGain)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBoxAmpType = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxAmpType.setEnabled(False)
        self.comboBoxAmpType.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBoxAmpType.setObjectName("comboBoxAmpType")
        self.comboBoxAmpType.addItem("")
        self.comboBoxAmpType.addItem("")
        self.verticalLayout_4.addWidget(self.comboBoxAmpType)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.formLayout)
        self.gridLayout.addWidget(self.groupBox_3, 2, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setStyleSheet("font: 11pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.checkBoxEM = QtWidgets.QCheckBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxEM.sizePolicy().hasHeightForWidth())
        self.checkBoxEM.setSizePolicy(sizePolicy)
        self.checkBoxEM.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }")
        self.checkBoxEM.setText("")
        self.checkBoxEM.setObjectName("checkBoxEM")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxEM)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setStyleSheet("font: 11pt \"Arial\";")
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.spinBox_averages = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_averages.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_averages.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_averages.setMinimum(1)
        self.spinBox_averages.setMaximum(100)
        self.spinBox_averages.setProperty("value", 1)
        self.spinBox_averages.setObjectName("spinBox_averages")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_averages)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.gridLayout.addWidget(self.groupBox_4, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxPreAmpGain.setCurrentIndex(-1)
        self.comboBoxAmpType.setCurrentIndex(1)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Acquisition Mode"))
        self.label_2.setText(_translate("Dialog", "Trigger Mode"))
        self.label_3.setText(_translate("Dialog", "Readout Mode"))
        self.groupBox.setTitle(_translate("Dialog", "Settings"))
        self.label_4.setText(_translate("Dialog", "Exposure Time (sec)"))
        self.label_12.setText(_translate("Dialog", "Baseline Clamping"))
        self.groupBox_2.setTitle(_translate("Dialog", "Vertical Pixel Shift"))
        self.label_5.setText(_translate("Dialog", "Shift Speed (us)"))
        self.label_6.setText(_translate("Dialog", "Vertical Clock Voltage Amplitude (V)"))
        self.groupBox_3.setTitle(_translate("Dialog", "Horizontal Pixel Shift"))
        self.label_8.setText(_translate("Dialog", "Readout Rate (MHz)"))
        self.label_9.setText(_translate("Dialog", "Premaplifer Gain"))
        self.label_7.setText(_translate("Dialog", "Output Amplifier"))
        self.comboBoxAmpType.setItemText(0, _translate("Dialog", "EM"))
        self.comboBoxAmpType.setItemText(1, _translate("Dialog", "Conventional"))
        self.groupBox_4.setTitle(_translate("Dialog", "EM Multiplier Gain"))
        self.label_10.setText(_translate("Dialog", "Enabled"))
        self.label_11.setText(_translate("Dialog", "Gain Level"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Camera Setup"))

