# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\qt_bcars2_spectroscopy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 909)
        MainWindow.setMinimumSize(QtCore.QSize(800, 400))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(391, 411))
        self.frame.setMaximumSize(QtCore.QSize(391, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_moveY = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveY.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_moveY.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_moveY.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveY.setStyleSheet("")
        self.pushButton_moveY.setObjectName("pushButton_moveY")
        self.gridLayout.addWidget(self.pushButton_moveY, 3, 4, 1, 1)
        self.pushButton_moveZ = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveZ.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_moveZ.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_moveZ.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveZ.setStyleSheet("")
        self.pushButton_moveZ.setObjectName("pushButton_moveZ")
        self.gridLayout.addWidget(self.pushButton_moveZ, 4, 4, 1, 1)
        self.spinBox_y_setpos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_y_setpos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_y_setpos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_y_setpos.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_y_setpos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_y_setpos.setReadOnly(False)
        self.spinBox_y_setpos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_y_setpos.setDecimals(3)
        self.spinBox_y_setpos.setMinimum(-10.0)
        self.spinBox_y_setpos.setMaximum(210.0)
        self.spinBox_y_setpos.setProperty("value", 100.0)
        self.spinBox_y_setpos.setObjectName("spinBox_y_setpos")
        self.gridLayout.addWidget(self.spinBox_y_setpos, 3, 3, 1, 1)
        self.pushButton_moveX = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_moveX.sizePolicy().hasHeightForWidth())
        self.pushButton_moveX.setSizePolicy(sizePolicy)
        self.pushButton_moveX.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_moveX.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_moveX.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveX.setStyleSheet("")
        self.pushButton_moveX.setObjectName("pushButton_moveX")
        self.gridLayout.addWidget(self.pushButton_moveX, 2, 4, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_moveAll = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveAll.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveAll.setStyleSheet("")
        self.pushButton_moveAll.setObjectName("pushButton_moveAll")
        self.horizontalLayout_2.addWidget(self.pushButton_moveAll)
        self.pushButton_setPos_getCurrent = QtWidgets.QPushButton(self.frame)
        self.pushButton_setPos_getCurrent.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_setPos_getCurrent.setStyleSheet("")
        self.pushButton_setPos_getCurrent.setObjectName("pushButton_setPos_getCurrent")
        self.horizontalLayout_2.addWidget(self.pushButton_setPos_getCurrent)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 2)
        self.spinBox_z_pos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_z_pos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_z_pos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_z_pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_z_pos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_z_pos.setReadOnly(True)
        self.spinBox_z_pos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_z_pos.setDecimals(3)
        self.spinBox_z_pos.setMinimum(-10.0)
        self.spinBox_z_pos.setMaximum(210.0)
        self.spinBox_z_pos.setProperty("value", 100.0)
        self.spinBox_z_pos.setObjectName("spinBox_z_pos")
        self.gridLayout.addWidget(self.spinBox_z_pos, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 2)
        self.spinBox_y_pos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_y_pos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_y_pos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_y_pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_y_pos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_y_pos.setReadOnly(True)
        self.spinBox_y_pos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_y_pos.setDecimals(3)
        self.spinBox_y_pos.setMinimum(-10.0)
        self.spinBox_y_pos.setMaximum(210.0)
        self.spinBox_y_pos.setProperty("value", 100.0)
        self.spinBox_y_pos.setObjectName("spinBox_y_pos")
        self.gridLayout.addWidget(self.spinBox_y_pos, 3, 1, 1, 1)
        self.spinBox_z_offset = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_z_offset.setMinimumSize(QtCore.QSize(50, 25))
        self.spinBox_z_offset.setMaximumSize(QtCore.QSize(150, 40))
        self.spinBox_z_offset.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_z_offset.setStyleSheet("")
        self.spinBox_z_offset.setReadOnly(False)
        self.spinBox_z_offset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_z_offset.setDecimals(3)
        self.spinBox_z_offset.setMinimum(-10.0)
        self.spinBox_z_offset.setMaximum(210.0)
        self.spinBox_z_offset.setProperty("value", 130.0)
        self.spinBox_z_offset.setObjectName("spinBox_z_offset")
        self.gridLayout.addWidget(self.spinBox_z_offset, 6, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 2)
        self.spinBox_x_pos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_x_pos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_x_pos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_x_pos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_x_pos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_x_pos.setReadOnly(True)
        self.spinBox_x_pos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_x_pos.setDecimals(3)
        self.spinBox_x_pos.setMinimum(-10.0)
        self.spinBox_x_pos.setMaximum(210.0)
        self.spinBox_x_pos.setProperty("value", 100.0)
        self.spinBox_x_pos.setObjectName("spinBox_x_pos")
        self.gridLayout.addWidget(self.spinBox_x_pos, 2, 1, 1, 1)
        self.spinBox_x_setpos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_x_setpos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_x_setpos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_x_setpos.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_x_setpos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_x_setpos.setReadOnly(False)
        self.spinBox_x_setpos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_x_setpos.setDecimals(3)
        self.spinBox_x_setpos.setMinimum(-10.0)
        self.spinBox_x_setpos.setMaximum(210.0)
        self.spinBox_x_setpos.setProperty("value", 100.0)
        self.spinBox_x_setpos.setObjectName("spinBox_x_setpos")
        self.gridLayout.addWidget(self.spinBox_x_setpos, 2, 3, 1, 1)
        self.pushButton_moveCenter = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveCenter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveCenter.setStyleSheet("")
        self.pushButton_moveCenter.setObjectName("pushButton_moveCenter")
        self.gridLayout.addWidget(self.pushButton_moveCenter, 5, 3, 1, 1)
        self.pushButton_updatePosition = QtWidgets.QPushButton(self.frame)
        self.pushButton_updatePosition.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_updatePosition.setObjectName("pushButton_updatePosition")
        self.gridLayout.addWidget(self.pushButton_updatePosition, 1, 0, 1, 2)
        self.spinBox_z_setpos = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_z_setpos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_z_setpos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_z_setpos.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.spinBox_z_setpos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_z_setpos.setReadOnly(False)
        self.spinBox_z_setpos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_z_setpos.setDecimals(3)
        self.spinBox_z_setpos.setMinimum(-10.0)
        self.spinBox_z_setpos.setMaximum(210.0)
        self.spinBox_z_setpos.setProperty("value", 100.0)
        self.spinBox_z_setpos.setObjectName("spinBox_z_setpos")
        self.gridLayout.addWidget(self.spinBox_z_setpos, 4, 3, 1, 1)
        self.pushButton_moveCenter_Offset = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveCenter_Offset.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveCenter_Offset.setStyleSheet("")
        self.pushButton_moveCenter_Offset.setObjectName("pushButton_moveCenter_Offset")
        self.gridLayout.addWidget(self.pushButton_moveCenter_Offset, 5, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 2, 5, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.spinBox_y_pos_micro = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_y_pos_micro.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_y_pos_micro.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_y_pos_micro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_y_pos_micro.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_y_pos_micro.setReadOnly(True)
        self.spinBox_y_pos_micro.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_y_pos_micro.setDecimals(3)
        self.spinBox_y_pos_micro.setMinimum(1.0)
        self.spinBox_y_pos_micro.setMaximum(24.0)
        self.spinBox_y_pos_micro.setProperty("value", 12.0)
        self.spinBox_y_pos_micro.setObjectName("spinBox_y_pos_micro")
        self.gridLayout_5.addWidget(self.spinBox_y_pos_micro, 4, 1, 1, 1)
        self.checkBoxJoyStickOn = QtWidgets.QCheckBox(self.frame)
        self.checkBoxJoyStickOn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxJoyStickOn.sizePolicy().hasHeightForWidth())
        self.checkBoxJoyStickOn.setSizePolicy(sizePolicy)
        self.checkBoxJoyStickOn.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxJoyStickOn.setText("")
        self.checkBoxJoyStickOn.setChecked(False)
        self.checkBoxJoyStickOn.setObjectName("checkBoxJoyStickOn")
        self.gridLayout_5.addWidget(self.checkBoxJoyStickOn, 5, 1, 1, 1)
        self.pushButton_moveYMicro = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveYMicro.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_moveYMicro.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_moveYMicro.setStyleSheet("")
        self.pushButton_moveYMicro.setObjectName("pushButton_moveYMicro")
        self.gridLayout_5.addWidget(self.pushButton_moveYMicro, 4, 4, 1, 1)
        self.pushButton_moveXMicro = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_moveXMicro.sizePolicy().hasHeightForWidth())
        self.pushButton_moveXMicro.setSizePolicy(sizePolicy)
        self.pushButton_moveXMicro.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_moveXMicro.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_moveXMicro.setStyleSheet("")
        self.pushButton_moveXMicro.setObjectName("pushButton_moveXMicro")
        self.gridLayout_5.addWidget(self.pushButton_moveXMicro, 3, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setTextFormat(QtCore.Qt.PlainText)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_moveAllMicro = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveAllMicro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_moveAllMicro.setStyleSheet("")
        self.pushButton_moveAllMicro.setObjectName("pushButton_moveAllMicro")
        self.horizontalLayout_6.addWidget(self.pushButton_moveAllMicro)
        self.pushButton_setPos_getCurrentMicro = QtWidgets.QPushButton(self.frame)
        self.pushButton_setPos_getCurrentMicro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_setPos_getCurrentMicro.setStyleSheet("")
        self.pushButton_setPos_getCurrentMicro.setObjectName("pushButton_setPos_getCurrentMicro")
        self.horizontalLayout_6.addWidget(self.pushButton_setPos_getCurrentMicro)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 2, 3, 1, 2)
        self.spinBox_x_setpos_micro = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_x_setpos_micro.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_x_setpos_micro.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_x_setpos_micro.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_x_setpos_micro.setReadOnly(False)
        self.spinBox_x_setpos_micro.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_x_setpos_micro.setDecimals(3)
        self.spinBox_x_setpos_micro.setMinimum(1.0)
        self.spinBox_x_setpos_micro.setMaximum(24.0)
        self.spinBox_x_setpos_micro.setProperty("value", 12.0)
        self.spinBox_x_setpos_micro.setObjectName("spinBox_x_setpos_micro")
        self.gridLayout_5.addWidget(self.spinBox_x_setpos_micro, 3, 3, 1, 1)
        self.pushButton_moveCenterMicro = QtWidgets.QPushButton(self.frame)
        self.pushButton_moveCenterMicro.setStyleSheet("")
        self.pushButton_moveCenterMicro.setObjectName("pushButton_moveCenterMicro")
        self.gridLayout_5.addWidget(self.pushButton_moveCenterMicro, 5, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("")
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("")
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 3, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 1, 2, 5, 1)
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self.pushButton_updateMicroPos = QtWidgets.QPushButton(self.frame)
        self.pushButton_updateMicroPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_updateMicroPos.setObjectName("pushButton_updateMicroPos")
        self.gridLayout_5.addWidget(self.pushButton_updateMicroPos, 2, 0, 1, 2)
        self.spinBox_y_setpos_micro = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_y_setpos_micro.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_y_setpos_micro.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_y_setpos_micro.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_y_setpos_micro.setReadOnly(False)
        self.spinBox_y_setpos_micro.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_y_setpos_micro.setDecimals(3)
        self.spinBox_y_setpos_micro.setMinimum(1.0)
        self.spinBox_y_setpos_micro.setMaximum(24.0)
        self.spinBox_y_setpos_micro.setProperty("value", 12.0)
        self.spinBox_y_setpos_micro.setObjectName("spinBox_y_setpos_micro")
        self.gridLayout_5.addWidget(self.spinBox_y_setpos_micro, 4, 3, 1, 1)
        self.spinBox_x_pos_micro = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinBox_x_pos_micro.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_x_pos_micro.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_x_pos_micro.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBox_x_pos_micro.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_x_pos_micro.setReadOnly(True)
        self.spinBox_x_pos_micro.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_x_pos_micro.setDecimals(3)
        self.spinBox_x_pos_micro.setMinimum(1.0)
        self.spinBox_x_pos_micro.setMaximum(24.0)
        self.spinBox_x_pos_micro.setProperty("value", 12.0)
        self.spinBox_x_pos_micro.setObjectName("spinBox_x_pos_micro")
        self.gridLayout_5.addWidget(self.spinBox_x_pos_micro, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 5, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.checkBoxAvgOn = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAvgOn.sizePolicy().hasHeightForWidth())
        self.checkBoxAvgOn.setSizePolicy(sizePolicy)
        self.checkBoxAvgOn.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxAvgOn.setText("")
        self.checkBoxAvgOn.setObjectName("checkBoxAvgOn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBoxAvgOn)
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinBoxNAverages = QtWidgets.QSpinBox(self.frame_2)
        self.spinBoxNAverages.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBoxNAverages.setStyleSheet("")
        self.spinBoxNAverages.setMinimum(2)
        self.spinBoxNAverages.setMaximum(1000)
        self.spinBoxNAverages.setProperty("value", 100)
        self.spinBoxNAverages.setObjectName("spinBoxNAverages")
        self.horizontalLayout_3.addWidget(self.spinBoxNAverages)
        self.radioButtonAvgDone = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonAvgDone.setEnabled(False)
        self.radioButtonAvgDone.setText("")
        self.radioButtonAvgDone.setCheckable(True)
        self.radioButtonAvgDone.setChecked(False)
        self.radioButtonAvgDone.setObjectName("radioButtonAvgDone")
        self.horizontalLayout_3.addWidget(self.radioButtonAvgDone)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.checkBoxShowStdDev = QtWidgets.QCheckBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxShowStdDev.sizePolicy().hasHeightForWidth())
        self.checkBoxShowStdDev.setSizePolicy(sizePolicy)
        self.checkBoxShowStdDev.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxShowStdDev.setText("")
        self.checkBoxShowStdDev.setObjectName("checkBoxShowStdDev")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBoxShowStdDev)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 0, 1, 1)
        self.pushButtonRecDark = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonRecDark.setObjectName("pushButtonRecDark")
        self.gridLayout_2.addWidget(self.pushButtonRecDark, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.checkBoxKK = QtWidgets.QCheckBox(self.frame_4)
        self.checkBoxKK.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxKK.sizePolicy().hasHeightForWidth())
        self.checkBoxKK.setSizePolicy(sizePolicy)
        self.checkBoxKK.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxKK.setText("")
        self.checkBoxKK.setObjectName("checkBoxKK")
        self.gridLayout_2.addWidget(self.checkBoxKK, 1, 1, 1, 1)
        self.checkBoxSubtractDark = QtWidgets.QCheckBox(self.frame_4)
        self.checkBoxSubtractDark.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSubtractDark.sizePolicy().hasHeightForWidth())
        self.checkBoxSubtractDark.setSizePolicy(sizePolicy)
        self.checkBoxSubtractDark.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxSubtractDark.setText("")
        self.checkBoxSubtractDark.setObjectName("checkBoxSubtractDark")
        self.gridLayout_2.addWidget(self.checkBoxSubtractDark, 0, 1, 1, 1)
        self.pushButtonRecNRB = QtWidgets.QPushButton(self.frame_4)
        self.pushButtonRecNRB.setObjectName("pushButtonRecNRB")
        self.gridLayout_2.addWidget(self.pushButtonRecNRB, 1, 2, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.spinBoxLowPix = QtWidgets.QSpinBox(self.frame_4)
        self.spinBoxLowPix.setMaximum(1599)
        self.spinBoxLowPix.setProperty("value", 0)
        self.spinBoxLowPix.setObjectName("spinBoxLowPix")
        self.horizontalLayout_7.addWidget(self.spinBoxLowPix)
        self.spinBoxHighPix = QtWidgets.QSpinBox(self.frame_4)
        self.spinBoxHighPix.setMaximum(1599)
        self.spinBoxHighPix.setProperty("value", 1599)
        self.spinBoxHighPix.setObjectName("spinBoxHighPix")
        self.horizontalLayout_7.addWidget(self.spinBoxHighPix)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.spinBoxTimeCurrPos = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxTimeCurrPos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxTimeCurrPos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBoxTimeCurrPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spinBoxTimeCurrPos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxTimeCurrPos.setReadOnly(True)
        self.spinBoxTimeCurrPos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTimeCurrPos.setDecimals(6)
        self.spinBoxTimeCurrPos.setMinimum(-10000.0)
        self.spinBoxTimeCurrPos.setMaximum(10000.0)
        self.spinBoxTimeCurrPos.setProperty("value", 0.0)
        self.spinBoxTimeCurrPos.setObjectName("spinBoxTimeCurrPos")
        self.gridLayout_3.addWidget(self.spinBoxTimeCurrPos, 0, 2, 1, 1)
        self.spinBoxTimeGoToPos = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxTimeGoToPos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxTimeGoToPos.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBoxTimeGoToPos.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.spinBoxTimeGoToPos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxTimeGoToPos.setReadOnly(False)
        self.spinBoxTimeGoToPos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxTimeGoToPos.setDecimals(3)
        self.spinBoxTimeGoToPos.setMinimum(-10000.0)
        self.spinBoxTimeGoToPos.setMaximum(10000.0)
        self.spinBoxTimeGoToPos.setProperty("value", -0.01)
        self.spinBoxTimeGoToPos.setObjectName("spinBoxTimeGoToPos")
        self.gridLayout_3.addWidget(self.spinBoxTimeGoToPos, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButtonTimeGoToPos = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeGoToPos.setObjectName("pushButtonTimeGoToPos")
        self.horizontalLayout_5.addWidget(self.pushButtonTimeGoToPos)
        self.pushButtonTimeSetZero = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeSetZero.setObjectName("pushButtonTimeSetZero")
        self.horizontalLayout_5.addWidget(self.pushButtonTimeSetZero)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 1, 1, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonTimeGoToEarly = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeGoToEarly.setObjectName("pushButtonTimeGoToEarly")
        self.verticalLayout_3.addWidget(self.pushButtonTimeGoToEarly)
        self.pushButtonTimeGoToZero = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeGoToZero.setObjectName("pushButtonTimeGoToZero")
        self.verticalLayout_3.addWidget(self.pushButtonTimeGoToZero)
        self.pushButtonTimeGoToLate = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeGoToLate.setObjectName("pushButtonTimeGoToLate")
        self.verticalLayout_3.addWidget(self.pushButtonTimeGoToLate)
        self.pushButtonTimeGoToDark = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonTimeGoToDark.setObjectName("pushButtonTimeGoToDark")
        self.verticalLayout_3.addWidget(self.pushButtonTimeGoToDark)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(391, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(391, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonStartAcq = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartAcq.sizePolicy().hasHeightForWidth())
        self.pushButtonStartAcq.setSizePolicy(sizePolicy)
        self.pushButtonStartAcq.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonStartAcq.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButtonStartAcq.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonStartAcq.setFont(font)
        self.pushButtonStartAcq.setStyleSheet("color: white;\n"
"font: 87 14pt \"Arial Black\";")
        self.pushButtonStartAcq.setObjectName("pushButtonStartAcq")
        self.horizontalLayout.addWidget(self.pushButtonStartAcq)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonStopAcq = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStopAcq.sizePolicy().hasHeightForWidth())
        self.pushButtonStopAcq.setSizePolicy(sizePolicy)
        self.pushButtonStopAcq.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonStopAcq.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButtonStopAcq.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonStopAcq.setFont(font)
        self.pushButtonStopAcq.setStyleSheet("color:red;\n"
"font: 87 14pt \"Arial Black\";")
        self.pushButtonStopAcq.setObjectName("pushButtonStopAcq")
        self.horizontalLayout.addWidget(self.pushButtonStopAcq)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.mpl_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy)
        self.mpl_widget.setAutoFillBackground(False)
        self.mpl_widget.setStyleSheet("background-color: rgb(53,53,53)")
        self.mpl_widget.setObjectName("mpl_widget")
        self.verticalLayout_6.addWidget(self.mpl_widget)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_6.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setMaximumSize(QtCore.QSize(161, 16777215))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.comboBoxSpectralXSelect = QtWidgets.QComboBox(self.frame_6)
        self.comboBoxSpectralXSelect.setMaximumSize(QtCore.QSize(161, 16777215))
        self.comboBoxSpectralXSelect.setObjectName("comboBoxSpectralXSelect")
        self.comboBoxSpectralXSelect.addItem("")
        self.comboBoxSpectralXSelect.addItem("")
        self.comboBoxSpectralXSelect.addItem("")
        self.verticalLayout_7.addWidget(self.comboBoxSpectralXSelect)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_7)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 21))
        self.menubar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBoxSpectralXSelect.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox_x_setpos, self.spinBox_y_setpos)
        MainWindow.setTabOrder(self.spinBox_y_setpos, self.spinBox_z_setpos)
        MainWindow.setTabOrder(self.spinBox_z_setpos, self.spinBox_y_pos_micro)
        MainWindow.setTabOrder(self.spinBox_y_pos_micro, self.spinBox_x_setpos_micro)
        MainWindow.setTabOrder(self.spinBox_x_setpos_micro, self.pushButton_moveCenterMicro)
        MainWindow.setTabOrder(self.pushButton_moveCenterMicro, self.spinBox_y_setpos_micro)
        MainWindow.setTabOrder(self.spinBox_y_setpos_micro, self.spinBox_x_pos_micro)
        MainWindow.setTabOrder(self.spinBox_x_pos_micro, self.checkBoxAvgOn)
        MainWindow.setTabOrder(self.checkBoxAvgOn, self.spinBoxNAverages)
        MainWindow.setTabOrder(self.spinBoxNAverages, self.radioButtonAvgDone)
        MainWindow.setTabOrder(self.radioButtonAvgDone, self.checkBoxShowStdDev)
        MainWindow.setTabOrder(self.checkBoxShowStdDev, self.pushButtonRecDark)
        MainWindow.setTabOrder(self.pushButtonRecDark, self.checkBoxKK)
        MainWindow.setTabOrder(self.checkBoxKK, self.checkBoxSubtractDark)
        MainWindow.setTabOrder(self.checkBoxSubtractDark, self.pushButtonRecNRB)
        MainWindow.setTabOrder(self.pushButtonRecNRB, self.spinBoxLowPix)
        MainWindow.setTabOrder(self.spinBoxLowPix, self.spinBoxHighPix)
        MainWindow.setTabOrder(self.spinBoxHighPix, self.spinBoxTimeCurrPos)
        MainWindow.setTabOrder(self.spinBoxTimeCurrPos, self.spinBoxTimeGoToPos)
        MainWindow.setTabOrder(self.spinBoxTimeGoToPos, self.pushButtonTimeGoToPos)
        MainWindow.setTabOrder(self.pushButtonTimeGoToPos, self.pushButtonTimeSetZero)
        MainWindow.setTabOrder(self.pushButtonTimeSetZero, self.pushButtonTimeGoToEarly)
        MainWindow.setTabOrder(self.pushButtonTimeGoToEarly, self.pushButtonTimeGoToZero)
        MainWindow.setTabOrder(self.pushButtonTimeGoToZero, self.pushButtonTimeGoToLate)
        MainWindow.setTabOrder(self.pushButtonTimeGoToLate, self.pushButtonTimeGoToDark)
        MainWindow.setTabOrder(self.pushButtonTimeGoToDark, self.pushButtonStartAcq)
        MainWindow.setTabOrder(self.pushButtonStartAcq, self.pushButtonStopAcq)
        MainWindow.setTabOrder(self.pushButtonStopAcq, self.comboBoxSpectralXSelect)
        MainWindow.setTabOrder(self.comboBoxSpectralXSelect, self.pushButton_moveYMicro)
        MainWindow.setTabOrder(self.pushButton_moveYMicro, self.checkBoxJoyStickOn)
        MainWindow.setTabOrder(self.checkBoxJoyStickOn, self.pushButton_moveXMicro)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_moveY.setText(_translate("MainWindow", "Move Y"))
        self.pushButton_moveZ.setText(_translate("MainWindow", "Move Z"))
        self.pushButton_moveX.setText(_translate("MainWindow", "Move X"))
        self.pushButton_moveAll.setText(_translate("MainWindow", "Move All"))
        self.pushButton_setPos_getCurrent.setText(_translate("MainWindow", "Use Current"))
        self.label_4.setText(_translate("MainWindow", "Current Position"))
        self.label_5.setText(_translate("MainWindow", "Set Position"))
        self.pushButton_moveCenter.setText(_translate("MainWindow", "Center"))
        self.pushButton_updatePosition.setText(_translate("MainWindow", "Update"))
        self.pushButton_moveCenter_Offset.setText(_translate("MainWindow", "Center + Z-Offset"))
        self.label_2.setText(_translate("MainWindow", "Y (um)"))
        self.label_3.setText(_translate("MainWindow", "X (um)"))
        self.label_7.setText(_translate("MainWindow", "Z (um)"))
        self.label_6.setText(_translate("MainWindow", "Z-Offset"))
        self.pushButton_moveYMicro.setText(_translate("MainWindow", "Move Y"))
        self.pushButton_moveXMicro.setText(_translate("MainWindow", "Move X"))
        self.label_15.setText(_translate("MainWindow", "Y (mm)"))
        self.pushButton_moveAllMicro.setText(_translate("MainWindow", "Move All"))
        self.pushButton_setPos_getCurrentMicro.setText(_translate("MainWindow", "Use Current"))
        self.pushButton_moveCenterMicro.setText(_translate("MainWindow", "Center"))
        self.label_13.setText(_translate("MainWindow", "Current Position"))
        self.label_14.setText(_translate("MainWindow", "Set Position"))
        self.label_16.setText(_translate("MainWindow", "X (mm)"))
        self.pushButton_updateMicroPos.setText(_translate("MainWindow", "Update"))
        self.label_17.setText(_translate("MainWindow", "Joy Stick"))
        self.label_18.setText(_translate("MainWindow", "Micro Stage"))
        self.label_8.setText(_translate("MainWindow", "Averages ON"))
        self.label_9.setText(_translate("MainWindow", "N Averages"))
        self.label_10.setText(_translate("MainWindow", "Show Standard Deviation"))
        self.label_19.setText(_translate("MainWindow", "Pixel Range [low, high]"))
        self.pushButtonRecDark.setText(_translate("MainWindow", "Record Dark"))
        self.label_11.setText(_translate("MainWindow", "Perform KK"))
        self.pushButtonRecNRB.setText(_translate("MainWindow", "Record NRB"))
        self.label_12.setText(_translate("MainWindow", "Subtract Dark"))
        self.groupBox.setTitle(_translate("MainWindow", "Time Delay"))
        self.label.setText(_translate("MainWindow", "Current Position (mm)"))
        self.pushButtonTimeGoToPos.setText(_translate("MainWindow", "Move"))
        self.pushButtonTimeSetZero.setText(_translate("MainWindow", "Set Zero"))
        self.pushButtonTimeGoToEarly.setText(_translate("MainWindow", "Early Time"))
        self.pushButtonTimeGoToZero.setText(_translate("MainWindow", "Zero Time"))
        self.pushButtonTimeGoToLate.setText(_translate("MainWindow", "Late Time"))
        self.pushButtonTimeGoToDark.setText(_translate("MainWindow", "Dark Time"))
        self.pushButtonStartAcq.setText(_translate("MainWindow", "Start"))
        self.pushButtonStopAcq.setText(_translate("MainWindow", "Stop"))
        self.label_20.setText(_translate("MainWindow", "Spectral Units"))
        self.comboBoxSpectralXSelect.setItemText(0, _translate("MainWindow", "Pixels (pix)"))
        self.comboBoxSpectralXSelect.setItemText(1, _translate("MainWindow", "Wavelength (nm)"))
        self.comboBoxSpectralXSelect.setItemText(2, _translate("MainWindow", "Wavenumber (cm-1)"))

