# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_designer\qt_bcars2_raster.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1511, 950)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBoxFast = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxFast.setObjectName("comboBoxFast")
        self.comboBoxFast.addItem("")
        self.comboBoxFast.addItem("")
        self.comboBoxFast.addItem("")
        self.verticalLayout.addWidget(self.comboBoxFast)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.spinBox_fast_start = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBox_fast_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fast_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fast_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fast_start.setReadOnly(False)
        self.spinBox_fast_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fast_start.setDecimals(3)
        self.spinBox_fast_start.setMinimum(-1.0)
        self.spinBox_fast_start.setMaximum(201.0)
        self.spinBox_fast_start.setProperty("value", 1.0)
        self.spinBox_fast_start.setObjectName("spinBox_fast_start")
        self.verticalLayout.addWidget(self.spinBox_fast_start)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinBox_fast_stop = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBox_fast_stop.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fast_stop.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fast_stop.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fast_stop.setReadOnly(False)
        self.spinBox_fast_stop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fast_stop.setDecimals(3)
        self.spinBox_fast_stop.setMinimum(-1.0)
        self.spinBox_fast_stop.setMaximum(201.0)
        self.spinBox_fast_stop.setProperty("value", 199.0)
        self.spinBox_fast_stop.setObjectName("spinBox_fast_stop")
        self.verticalLayout.addWidget(self.spinBox_fast_stop)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.spinBox_fast_steps = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_fast_steps.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_fast_steps.setMinimum(1)
        self.spinBox_fast_steps.setMaximum(5000)
        self.spinBox_fast_steps.setProperty("value", 50)
        self.spinBox_fast_steps.setObjectName("spinBox_fast_steps")
        self.verticalLayout.addWidget(self.spinBox_fast_steps)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.spinBox_fast_stepsize = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBox_fast_stepsize.setEnabled(False)
        self.spinBox_fast_stepsize.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fast_stepsize.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fast_stepsize.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fast_stepsize.setReadOnly(True)
        self.spinBox_fast_stepsize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fast_stepsize.setDecimals(3)
        self.spinBox_fast_stepsize.setMinimum(-200.0)
        self.spinBox_fast_stepsize.setMaximum(200.0)
        self.spinBox_fast_stepsize.setProperty("value", 1.0)
        self.spinBox_fast_stepsize.setObjectName("spinBox_fast_stepsize")
        self.verticalLayout.addWidget(self.spinBox_fast_stepsize)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_9.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.comboBoxSlow = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxSlow.setObjectName("comboBoxSlow")
        self.comboBoxSlow.addItem("")
        self.comboBoxSlow.addItem("")
        self.comboBoxSlow.addItem("")
        self.verticalLayout_5.addWidget(self.comboBoxSlow)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.spinBox_slow_start = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_slow_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_slow_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_slow_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_slow_start.setReadOnly(False)
        self.spinBox_slow_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_slow_start.setDecimals(3)
        self.spinBox_slow_start.setMinimum(-1.0)
        self.spinBox_slow_start.setMaximum(201.0)
        self.spinBox_slow_start.setProperty("value", 1.0)
        self.spinBox_slow_start.setObjectName("spinBox_slow_start")
        self.verticalLayout_5.addWidget(self.spinBox_slow_start)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.spinBox_slow_stop = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_slow_stop.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_slow_stop.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_slow_stop.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_slow_stop.setReadOnly(False)
        self.spinBox_slow_stop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_slow_stop.setDecimals(3)
        self.spinBox_slow_stop.setMinimum(-1.0)
        self.spinBox_slow_stop.setMaximum(201.0)
        self.spinBox_slow_stop.setProperty("value", 199.0)
        self.spinBox_slow_stop.setObjectName("spinBox_slow_stop")
        self.verticalLayout_5.addWidget(self.spinBox_slow_stop)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.spinBox_slow_steps = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_slow_steps.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_slow_steps.setMinimum(1)
        self.spinBox_slow_steps.setMaximum(5000)
        self.spinBox_slow_steps.setProperty("value", 50)
        self.spinBox_slow_steps.setObjectName("spinBox_slow_steps")
        self.verticalLayout_5.addWidget(self.spinBox_slow_steps)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.spinBox_slow_stepsize = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBox_slow_stepsize.setEnabled(False)
        self.spinBox_slow_stepsize.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_slow_stepsize.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_slow_stepsize.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_slow_stepsize.setReadOnly(True)
        self.spinBox_slow_stepsize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_slow_stepsize.setDecimals(3)
        self.spinBox_slow_stepsize.setMinimum(-200.0)
        self.spinBox_slow_stepsize.setMaximum(200.0)
        self.spinBox_slow_stepsize.setProperty("value", 1.0)
        self.spinBox_slow_stepsize.setObjectName("spinBox_slow_stepsize")
        self.verticalLayout_5.addWidget(self.spinBox_slow_stepsize)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_9)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.comboBoxFixed = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBoxFixed.setObjectName("comboBoxFixed")
        self.comboBoxFixed.addItem("")
        self.comboBoxFixed.addItem("")
        self.comboBoxFixed.addItem("")
        self.verticalLayout_3.addWidget(self.comboBoxFixed)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.spinBox_fixed_start = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_fixed_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fixed_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fixed_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fixed_start.setReadOnly(False)
        self.spinBox_fixed_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fixed_start.setDecimals(3)
        self.spinBox_fixed_start.setMinimum(-1.0)
        self.spinBox_fixed_start.setMaximum(201.0)
        self.spinBox_fixed_start.setProperty("value", 100.0)
        self.spinBox_fixed_start.setObjectName("spinBox_fixed_start")
        self.verticalLayout_3.addWidget(self.spinBox_fixed_start)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.spinBox_fixed_stop = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_fixed_stop.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fixed_stop.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fixed_stop.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fixed_stop.setReadOnly(False)
        self.spinBox_fixed_stop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fixed_stop.setDecimals(3)
        self.spinBox_fixed_stop.setMinimum(-1.0)
        self.spinBox_fixed_stop.setMaximum(201.0)
        self.spinBox_fixed_stop.setProperty("value", 100.0)
        self.spinBox_fixed_stop.setObjectName("spinBox_fixed_stop")
        self.verticalLayout_3.addWidget(self.spinBox_fixed_stop)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.spinBox_fixed_steps = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_fixed_steps.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_fixed_steps.setMinimum(1)
        self.spinBox_fixed_steps.setMaximum(5000)
        self.spinBox_fixed_steps.setProperty("value", 1)
        self.spinBox_fixed_steps.setObjectName("spinBox_fixed_steps")
        self.verticalLayout_3.addWidget(self.spinBox_fixed_steps)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.spinBox_fixed_stepsize = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_fixed_stepsize.setEnabled(False)
        self.spinBox_fixed_stepsize.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_fixed_stepsize.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_fixed_stepsize.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_fixed_stepsize.setReadOnly(True)
        self.spinBox_fixed_stepsize.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_fixed_stepsize.setDecimals(3)
        self.spinBox_fixed_stepsize.setMinimum(-200.0)
        self.spinBox_fixed_stepsize.setMaximum(200.0)
        self.spinBox_fixed_stepsize.setProperty("value", 1.0)
        self.spinBox_fixed_stepsize.setObjectName("spinBox_fixed_stepsize")
        self.verticalLayout_3.addWidget(self.spinBox_fixed_stepsize)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_10)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonMacroXZ = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroXZ.setObjectName("pushButtonMacroXZ")
        self.gridLayout.addWidget(self.pushButtonMacroXZ, 0, 1, 1, 1)
        self.pushButtonMacroXY = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroXY.setObjectName("pushButtonMacroXY")
        self.gridLayout.addWidget(self.pushButtonMacroXY, 0, 0, 1, 1)
        self.pushButtonMacroHighRes = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroHighRes.setObjectName("pushButtonMacroHighRes")
        self.gridLayout.addWidget(self.pushButtonMacroHighRes, 1, 1, 1, 1)
        self.pushButtonMacroLowRes = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroLowRes.setObjectName("pushButtonMacroLowRes")
        self.gridLayout.addWidget(self.pushButtonMacroLowRes, 1, 0, 1, 1)
        self.pushButtonMacroXYRange = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroXYRange.setObjectName("pushButtonMacroXYRange")
        self.gridLayout.addWidget(self.pushButtonMacroXYRange, 3, 0, 1, 1)
        self.pushButtonMacroXZRange = QtWidgets.QPushButton(self.tab_10)
        self.pushButtonMacroXZRange.setObjectName("pushButtonMacroXZRange")
        self.gridLayout.addWidget(self.pushButtonMacroXZRange, 3, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, "")
        self.verticalLayout_12.addWidget(self.tabWidget_3)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.formLayout = QtWidgets.QFormLayout(self.tab_7)
        self.formLayout.setObjectName("formLayout")
        self.label_14 = QtWidgets.QLabel(self.tab_7)
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox_post_image_z_pos = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.spinBox_post_image_z_pos.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_post_image_z_pos.setMaximumSize(QtCore.QSize(75, 40))
        self.spinBox_post_image_z_pos.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_post_image_z_pos.setReadOnly(False)
        self.spinBox_post_image_z_pos.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_post_image_z_pos.setDecimals(3)
        self.spinBox_post_image_z_pos.setMinimum(-1.0)
        self.spinBox_post_image_z_pos.setMaximum(201.0)
        self.spinBox_post_image_z_pos.setProperty("value", 130.0)
        self.spinBox_post_image_z_pos.setObjectName("spinBox_post_image_z_pos")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_post_image_z_pos)
        self.label_16 = QtWidgets.QLabel(self.tab_7)
        self.label_16.setTextFormat(QtCore.Qt.PlainText)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.spinBoxDelayImaging = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.spinBoxDelayImaging.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxDelayImaging.setMaximumSize(QtCore.QSize(75, 40))
        self.spinBoxDelayImaging.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxDelayImaging.setReadOnly(False)
        self.spinBoxDelayImaging.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDelayImaging.setDecimals(3)
        self.spinBoxDelayImaging.setMinimum(-10000.0)
        self.spinBoxDelayImaging.setMaximum(10000.0)
        self.spinBoxDelayImaging.setProperty("value", -0.29)
        self.spinBoxDelayImaging.setObjectName("spinBoxDelayImaging")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxDelayImaging)
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.comboBoxRecNRB = QtWidgets.QComboBox(self.tab_7)
        self.comboBoxRecNRB.setMaximumSize(QtCore.QSize(69, 16777215))
        self.comboBoxRecNRB.setObjectName("comboBoxRecNRB")
        self.comboBoxRecNRB.addItem("")
        self.comboBoxRecNRB.addItem("")
        self.comboBoxRecNRB.addItem("")
        self.comboBoxRecNRB.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBoxRecNRB)
        self.label_17 = QtWidgets.QLabel(self.tab_7)
        self.label_17.setTextFormat(QtCore.Qt.PlainText)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxCollectDark = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxCollectDark.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCollectDark.sizePolicy().hasHeightForWidth())
        self.checkBoxCollectDark.setSizePolicy(sizePolicy)
        self.checkBoxCollectDark.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxCollectDark.setText("")
        self.checkBoxCollectDark.setObjectName("checkBoxCollectDark")
        self.horizontalLayout.addWidget(self.checkBoxCollectDark)
        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setTextFormat(QtCore.Qt.PlainText)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.spinBoxDelayDark = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.spinBoxDelayDark.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxDelayDark.setMaximumSize(QtCore.QSize(75, 40))
        self.spinBoxDelayDark.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxDelayDark.setReadOnly(False)
        self.spinBoxDelayDark.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDelayDark.setDecimals(3)
        self.spinBoxDelayDark.setMinimum(-10000.0)
        self.spinBoxDelayDark.setMaximum(10000.0)
        self.spinBoxDelayDark.setProperty("value", 0.3)
        self.spinBoxDelayDark.setObjectName("spinBoxDelayDark")
        self.horizontalLayout.addWidget(self.spinBoxDelayDark)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_18 = QtWidgets.QLabel(self.tab_7)
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxCollectNRB = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxCollectNRB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCollectNRB.sizePolicy().hasHeightForWidth())
        self.checkBoxCollectNRB.setSizePolicy(sizePolicy)
        self.checkBoxCollectNRB.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxCollectNRB.setText("")
        self.checkBoxCollectNRB.setObjectName("checkBoxCollectNRB")
        self.horizontalLayout_3.addWidget(self.checkBoxCollectNRB)
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setTextFormat(QtCore.Qt.PlainText)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_3.addWidget(self.label_22)
        self.spinBoxDelayNRB = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.spinBoxDelayNRB.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxDelayNRB.setMaximumSize(QtCore.QSize(75, 40))
        self.spinBoxDelayNRB.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxDelayNRB.setReadOnly(False)
        self.spinBoxDelayNRB.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDelayNRB.setDecimals(3)
        self.spinBoxDelayNRB.setMinimum(-10000.0)
        self.spinBoxDelayNRB.setMaximum(10000.0)
        self.spinBoxDelayNRB.setProperty("value", -0.29)
        self.spinBoxDelayNRB.setObjectName("spinBoxDelayNRB")
        self.horizontalLayout_3.addWidget(self.spinBoxDelayNRB)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setTextFormat(QtCore.Qt.PlainText)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBoxCollectNRB_Early = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxCollectNRB_Early.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxCollectNRB_Early.sizePolicy().hasHeightForWidth())
        self.checkBoxCollectNRB_Early.setSizePolicy(sizePolicy)
        self.checkBoxCollectNRB_Early.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxCollectNRB_Early.setText("")
        self.checkBoxCollectNRB_Early.setObjectName("checkBoxCollectNRB_Early")
        self.horizontalLayout_4.addWidget(self.checkBoxCollectNRB_Early)
        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setTextFormat(QtCore.Qt.PlainText)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.spinBoxDelayNRB_Early = QtWidgets.QDoubleSpinBox(self.tab_7)
        self.spinBoxDelayNRB_Early.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBoxDelayNRB_Early.setMaximumSize(QtCore.QSize(75, 40))
        self.spinBoxDelayNRB_Early.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBoxDelayNRB_Early.setReadOnly(False)
        self.spinBoxDelayNRB_Early.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxDelayNRB_Early.setDecimals(3)
        self.spinBoxDelayNRB_Early.setMinimum(-10000.0)
        self.spinBoxDelayNRB_Early.setMaximum(10000.0)
        self.spinBoxDelayNRB_Early.setProperty("value", 0.01)
        self.spinBoxDelayNRB_Early.setObjectName("spinBoxDelayNRB_Early")
        self.horizontalLayout_4.addWidget(self.spinBoxDelayNRB_Early)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_31 = QtWidgets.QLabel(self.groupBox_4)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_14.addWidget(self.label_31)
        self.comboBox_nrb_fast_axis = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_nrb_fast_axis.setEnabled(False)
        self.comboBox_nrb_fast_axis.setObjectName("comboBox_nrb_fast_axis")
        self.comboBox_nrb_fast_axis.addItem("")
        self.comboBox_nrb_fast_axis.addItem("")
        self.comboBox_nrb_fast_axis.addItem("")
        self.verticalLayout_14.addWidget(self.comboBox_nrb_fast_axis)
        self.label_32 = QtWidgets.QLabel(self.groupBox_4)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_14.addWidget(self.label_32)
        self.spinBox_nrb_fast_start = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinBox_nrb_fast_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_nrb_fast_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_nrb_fast_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_nrb_fast_start.setReadOnly(False)
        self.spinBox_nrb_fast_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_fast_start.setDecimals(3)
        self.spinBox_nrb_fast_start.setMinimum(-1.0)
        self.spinBox_nrb_fast_start.setMaximum(201.0)
        self.spinBox_nrb_fast_start.setProperty("value", 90.0)
        self.spinBox_nrb_fast_start.setObjectName("spinBox_nrb_fast_start")
        self.verticalLayout_14.addWidget(self.spinBox_nrb_fast_start)
        self.label_33 = QtWidgets.QLabel(self.groupBox_4)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_14.addWidget(self.label_33)
        self.spinBox_nrb_fast_stop = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.spinBox_nrb_fast_stop.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_nrb_fast_stop.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_nrb_fast_stop.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_nrb_fast_stop.setReadOnly(False)
        self.spinBox_nrb_fast_stop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_fast_stop.setDecimals(3)
        self.spinBox_nrb_fast_stop.setMinimum(-1.0)
        self.spinBox_nrb_fast_stop.setMaximum(201.0)
        self.spinBox_nrb_fast_stop.setProperty("value", 110.0)
        self.spinBox_nrb_fast_stop.setObjectName("spinBox_nrb_fast_stop")
        self.verticalLayout_14.addWidget(self.spinBox_nrb_fast_stop)
        self.label_34 = QtWidgets.QLabel(self.groupBox_4)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_14.addWidget(self.label_34)
        self.spinBox_nrb_fast_steps = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_nrb_fast_steps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_fast_steps.setMinimum(1)
        self.spinBox_nrb_fast_steps.setMaximum(5000)
        self.spinBox_nrb_fast_steps.setProperty("value", 120)
        self.spinBox_nrb_fast_steps.setObjectName("spinBox_nrb_fast_steps")
        self.verticalLayout_14.addWidget(self.spinBox_nrb_fast_steps)
        self.verticalLayout_13.addLayout(self.verticalLayout_14)
        self.horizontalLayout_8.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_16.addWidget(self.label_36)
        self.comboBox_nrb_slow_axis = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_nrb_slow_axis.setEnabled(False)
        self.comboBox_nrb_slow_axis.setObjectName("comboBox_nrb_slow_axis")
        self.comboBox_nrb_slow_axis.addItem("")
        self.comboBox_nrb_slow_axis.addItem("")
        self.comboBox_nrb_slow_axis.addItem("")
        self.verticalLayout_16.addWidget(self.comboBox_nrb_slow_axis)
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_16.addWidget(self.label_37)
        self.spinBox_nrb_slow_start = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinBox_nrb_slow_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_nrb_slow_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_nrb_slow_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_nrb_slow_start.setReadOnly(False)
        self.spinBox_nrb_slow_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_slow_start.setDecimals(3)
        self.spinBox_nrb_slow_start.setMinimum(-1.0)
        self.spinBox_nrb_slow_start.setMaximum(201.0)
        self.spinBox_nrb_slow_start.setProperty("value", 90.0)
        self.spinBox_nrb_slow_start.setObjectName("spinBox_nrb_slow_start")
        self.verticalLayout_16.addWidget(self.spinBox_nrb_slow_start)
        self.label_38 = QtWidgets.QLabel(self.groupBox_5)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_16.addWidget(self.label_38)
        self.spinBox_nrb_slow_stop = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.spinBox_nrb_slow_stop.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_nrb_slow_stop.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_nrb_slow_stop.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_nrb_slow_stop.setReadOnly(False)
        self.spinBox_nrb_slow_stop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_slow_stop.setDecimals(3)
        self.spinBox_nrb_slow_stop.setMinimum(-1.0)
        self.spinBox_nrb_slow_stop.setMaximum(201.0)
        self.spinBox_nrb_slow_stop.setProperty("value", 110.0)
        self.spinBox_nrb_slow_stop.setObjectName("spinBox_nrb_slow_stop")
        self.verticalLayout_16.addWidget(self.spinBox_nrb_slow_stop)
        self.label_39 = QtWidgets.QLabel(self.groupBox_5)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_16.addWidget(self.label_39)
        self.spinBox_nrb_slow_steps = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_nrb_slow_steps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_slow_steps.setMinimum(1)
        self.spinBox_nrb_slow_steps.setMaximum(5000)
        self.spinBox_nrb_slow_steps.setProperty("value", 5)
        self.spinBox_nrb_slow_steps.setObjectName("spinBox_nrb_slow_steps")
        self.verticalLayout_16.addWidget(self.spinBox_nrb_slow_steps)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_18.addWidget(self.label_41)
        self.comboBox_nrb_fixed_axis = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_nrb_fixed_axis.setEnabled(False)
        self.comboBox_nrb_fixed_axis.setObjectName("comboBox_nrb_fixed_axis")
        self.comboBox_nrb_fixed_axis.addItem("")
        self.comboBox_nrb_fixed_axis.addItem("")
        self.comboBox_nrb_fixed_axis.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_nrb_fixed_axis)
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_18.addWidget(self.label_42)
        self.spinBox_nrb_fixed_start = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.spinBox_nrb_fixed_start.setMinimumSize(QtCore.QSize(75, 25))
        self.spinBox_nrb_fixed_start.setMaximumSize(QtCore.QSize(200, 40))
        self.spinBox_nrb_fixed_start.setStyleSheet("font: 11pt \"Arial\";")
        self.spinBox_nrb_fixed_start.setReadOnly(False)
        self.spinBox_nrb_fixed_start.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_nrb_fixed_start.setDecimals(3)
        self.spinBox_nrb_fixed_start.setMinimum(-1.0)
        self.spinBox_nrb_fixed_start.setMaximum(201.0)
        self.spinBox_nrb_fixed_start.setProperty("value", 100.0)
        self.spinBox_nrb_fixed_start.setObjectName("spinBox_nrb_fixed_start")
        self.verticalLayout_18.addWidget(self.spinBox_nrb_fixed_start)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.horizontalLayout_8.addWidget(self.groupBox_6)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.verticalLayout_12.addWidget(self.tabWidget_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(1000, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonStartAcq = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartAcq.sizePolicy().hasHeightForWidth())
        self.pushButtonStartAcq.setSizePolicy(sizePolicy)
        self.pushButtonStartAcq.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonStartAcq.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButtonStartAcq.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonStartAcq.setFont(font)
        self.pushButtonStartAcq.setStyleSheet("color: white;\n"
"font: 87 14pt \"Arial Black\";")
        self.pushButtonStartAcq.setObjectName("pushButtonStartAcq")
        self.horizontalLayout_2.addWidget(self.pushButtonStartAcq)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonStopAcq = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStopAcq.sizePolicy().hasHeightForWidth())
        self.pushButtonStopAcq.setSizePolicy(sizePolicy)
        self.pushButtonStopAcq.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButtonStopAcq.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButtonStopAcq.setBaseSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButtonStopAcq.setFont(font)
        self.pushButtonStopAcq.setStyleSheet("color:red;\n"
"font: 87 14pt \"Arial Black\";")
        self.pushButtonStopAcq.setCheckable(True)
        self.pushButtonStopAcq.setChecked(False)
        self.pushButtonStopAcq.setObjectName("pushButtonStopAcq")
        self.horizontalLayout_2.addWidget(self.pushButtonStopAcq)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_12.addWidget(self.frame_3)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_7.addWidget(self.label_30, 0, QtCore.Qt.AlignLeft)
        self.checkBoxSave = QtWidgets.QCheckBox(self.tab_5)
        self.checkBoxSave.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSave.sizePolicy().hasHeightForWidth())
        self.checkBoxSave.setSizePolicy(sizePolicy)
        self.checkBoxSave.setStyleSheet("QCheckBox::indicator { width: 25; height: 25 }\n"
"QCheckBox::indicator:disabled { background-color:rgb(100,100,100);}")
        self.checkBoxSave.setText("")
        self.checkBoxSave.setChecked(False)
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.horizontalLayout_7.addWidget(self.checkBoxSave, 0, QtCore.Qt.AlignLeft)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_11.addWidget(self.label_26)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditPathFileName = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditPathFileName.setClearButtonEnabled(False)
        self.lineEditPathFileName.setObjectName("lineEditPathFileName")
        self.horizontalLayout_5.addWidget(self.lineEditPathFileName)
        self.pushButtonBrowseFiles = QtWidgets.QPushButton(self.tab_5)
        self.pushButtonBrowseFiles.setMinimumSize(QtCore.QSize(25, 0))
        self.pushButtonBrowseFiles.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonBrowseFiles.setObjectName("pushButtonBrowseFiles")
        self.horizontalLayout_5.addWidget(self.pushButtonBrowseFiles)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.lineEditDatasetName = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditDatasetName.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditDatasetName.setObjectName("lineEditDatasetName")
        self.verticalLayout_10.addWidget(self.lineEditDatasetName)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_9.addWidget(self.label_28)
        self.spinBoxDatasetIndex = QtWidgets.QSpinBox(self.tab_5)
        self.spinBoxDatasetIndex.setMaximum(5000)
        self.spinBoxDatasetIndex.setObjectName("spinBoxDatasetIndex")
        self.verticalLayout_9.addWidget(self.spinBoxDatasetIndex)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_11.addWidget(self.label_29)
        self.lineEditGroupName = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditGroupName.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEditGroupName.setObjectName("lineEditGroupName")
        self.verticalLayout_11.addWidget(self.lineEditGroupName)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.plainTextEditMemo = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEditMemo.setObjectName("plainTextEditMemo")
        self.gridLayout_5.addWidget(self.plainTextEditMemo, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(739, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget_left = QtWidgets.QTabWidget(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.tabWidget_left.setFont(font)
        self.tabWidget_left.setObjectName("tabWidget_left")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mpl_widget_left = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget_left.sizePolicy().hasHeightForWidth())
        self.mpl_widget_left.setSizePolicy(sizePolicy)
        self.mpl_widget_left.setMinimumSize(QtCore.QSize(518, 451))
        self.mpl_widget_left.setAutoFillBackground(False)
        self.mpl_widget_left.setStyleSheet("background-color: rgb(53,53,53)")
        self.mpl_widget_left.setObjectName("mpl_widget_left")
        self.gridLayout_2.addWidget(self.mpl_widget_left, 0, 0, 1, 1)
        self.tabWidget_left.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinBox_left_index = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_left_index.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBox_left_index.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_left_index.setMinimum(0)
        self.spinBox_left_index.setMaximum(1599)
        self.spinBox_left_index.setProperty("value", 1000)
        self.spinBox_left_index.setObjectName("spinBox_left_index")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_left_index)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.tabWidget_left.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget_left, 0, 0, 1, 1)
        self.tabWidget_right = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget_right.setObjectName("tabWidget_right")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mpl_widget_right = QtWidgets.QWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget_right.sizePolicy().hasHeightForWidth())
        self.mpl_widget_right.setSizePolicy(sizePolicy)
        self.mpl_widget_right.setMinimumSize(QtCore.QSize(518, 451))
        self.mpl_widget_right.setAutoFillBackground(False)
        self.mpl_widget_right.setStyleSheet("background-color: rgb(53,53,53)")
        self.mpl_widget_right.setObjectName("mpl_widget_right")
        self.gridLayout_3.addWidget(self.mpl_widget_right, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setObjectName("label_35")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.spinBox_right_index = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_right_index.setMaximumSize(QtCore.QSize(61, 16777215))
        self.spinBox_right_index.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBox_right_index.setMinimum(0)
        self.spinBox_right_index.setMaximum(1599)
        self.spinBox_right_index.setProperty("value", 1000)
        self.spinBox_right_index.setObjectName("spinBox_right_index")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_right_index)
        self.gridLayout_7.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.tabWidget_right.addTab(self.tab_4, "")
        self.gridLayout_4.addWidget(self.tabWidget_right, 0, 1, 1, 1)
        self.mpl_widget_spectra = QtWidgets.QWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget_spectra.sizePolicy().hasHeightForWidth())
        self.mpl_widget_spectra.setSizePolicy(sizePolicy)
        self.mpl_widget_spectra.setMinimumSize(QtCore.QSize(1061, 281))
        self.mpl_widget_spectra.setAutoFillBackground(False)
        self.mpl_widget_spectra.setStyleSheet("background-color: rgb(53,53,53)")
        self.mpl_widget_spectra.setObjectName("mpl_widget_spectra")
        self.gridLayout_4.addWidget(self.mpl_widget_spectra, 1, 0, 1, 2)
        self.gridLayout_6.addWidget(self.frame_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1511, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.comboBoxSlow.setCurrentIndex(1)
        self.comboBoxFixed.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(0)
        self.comboBoxRecNRB.setCurrentIndex(0)
        self.comboBox_nrb_slow_axis.setCurrentIndex(1)
        self.comboBox_nrb_fixed_axis.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_left.setCurrentIndex(0)
        self.tabWidget_right.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxFast, self.spinBox_fast_start)
        MainWindow.setTabOrder(self.spinBox_fast_start, self.spinBox_fast_stop)
        MainWindow.setTabOrder(self.spinBox_fast_stop, self.spinBox_fast_steps)
        MainWindow.setTabOrder(self.spinBox_fast_steps, self.comboBoxSlow)
        MainWindow.setTabOrder(self.comboBoxSlow, self.spinBox_slow_start)
        MainWindow.setTabOrder(self.spinBox_slow_start, self.spinBox_slow_stop)
        MainWindow.setTabOrder(self.spinBox_slow_stop, self.spinBox_slow_steps)
        MainWindow.setTabOrder(self.spinBox_slow_steps, self.comboBoxFixed)
        MainWindow.setTabOrder(self.comboBoxFixed, self.spinBox_fixed_start)
        MainWindow.setTabOrder(self.spinBox_fixed_start, self.spinBox_fixed_stop)
        MainWindow.setTabOrder(self.spinBox_fixed_stop, self.spinBox_fixed_steps)
        MainWindow.setTabOrder(self.spinBox_fixed_steps, self.spinBox_post_image_z_pos)
        MainWindow.setTabOrder(self.spinBox_post_image_z_pos, self.spinBoxDelayImaging)
        MainWindow.setTabOrder(self.spinBoxDelayImaging, self.comboBoxRecNRB)
        MainWindow.setTabOrder(self.comboBoxRecNRB, self.checkBoxCollectDark)
        MainWindow.setTabOrder(self.checkBoxCollectDark, self.spinBoxDelayDark)
        MainWindow.setTabOrder(self.spinBoxDelayDark, self.checkBoxCollectNRB)
        MainWindow.setTabOrder(self.checkBoxCollectNRB, self.spinBoxDelayNRB)
        MainWindow.setTabOrder(self.spinBoxDelayNRB, self.checkBoxCollectNRB_Early)
        MainWindow.setTabOrder(self.checkBoxCollectNRB_Early, self.spinBoxDelayNRB_Early)
        MainWindow.setTabOrder(self.spinBoxDelayNRB_Early, self.pushButtonStartAcq)
        MainWindow.setTabOrder(self.pushButtonStartAcq, self.pushButtonStopAcq)
        MainWindow.setTabOrder(self.pushButtonStopAcq, self.tabWidget_left)
        MainWindow.setTabOrder(self.tabWidget_left, self.tabWidget_right)
        MainWindow.setTabOrder(self.tabWidget_right, self.spinBox_left_index)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Raster Scanning"))
        self.groupBox.setTitle(_translate("MainWindow", "Fast Axis"))
        self.label_4.setText(_translate("MainWindow", "Axis"))
        self.comboBoxFast.setItemText(0, _translate("MainWindow", "X"))
        self.comboBoxFast.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBoxFast.setItemText(2, _translate("MainWindow", "Z"))
        self.label.setText(_translate("MainWindow", "Start (um)"))
        self.label_2.setText(_translate("MainWindow", "Stop (um)"))
        self.label_3.setText(_translate("MainWindow", "Steps"))
        self.label_15.setText(_translate("MainWindow", "Step Size (um)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Slow Axis"))
        self.label_5.setText(_translate("MainWindow", "Axis"))
        self.comboBoxSlow.setItemText(0, _translate("MainWindow", "X"))
        self.comboBoxSlow.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBoxSlow.setItemText(2, _translate("MainWindow", "Z"))
        self.label_6.setText(_translate("MainWindow", "Start (um)"))
        self.label_7.setText(_translate("MainWindow", "Stop (um)"))
        self.label_8.setText(_translate("MainWindow", "Steps"))
        self.label_24.setText(_translate("MainWindow", "Step Size (um)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fixed Axis"))
        self.label_9.setText(_translate("MainWindow", "Axis"))
        self.comboBoxFixed.setItemText(0, _translate("MainWindow", "X"))
        self.comboBoxFixed.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBoxFixed.setItemText(2, _translate("MainWindow", "Z"))
        self.label_10.setText(_translate("MainWindow", "Start (um)"))
        self.label_11.setText(_translate("MainWindow", "Stop (um)"))
        self.label_12.setText(_translate("MainWindow", "Steps"))
        self.label_25.setText(_translate("MainWindow", "Step Size (um)"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Raster Parameters"))
        self.pushButtonMacroXZ.setText(_translate("MainWindow", "X-Z"))
        self.pushButtonMacroXY.setText(_translate("MainWindow", "X-Y"))
        self.pushButtonMacroHighRes.setText(_translate("MainWindow", "High Res"))
        self.pushButtonMacroLowRes.setText(_translate("MainWindow", "Low Res"))
        self.pushButtonMacroXYRange.setText(_translate("MainWindow", "Full XY Range"))
        self.pushButtonMacroXZRange.setText(_translate("MainWindow", "XZ Range"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Macros"))
        self.label_14.setText(_translate("MainWindow", "Post-Image Z  (um)"))
        self.label_16.setText(_translate("MainWindow", "Imaging Delay (mm)"))
        self.label_19.setText(_translate("MainWindow", "Before/After"))
        self.comboBoxRecNRB.setItemText(0, _translate("MainWindow", "None"))
        self.comboBoxRecNRB.setItemText(1, _translate("MainWindow", "Before"))
        self.comboBoxRecNRB.setItemText(2, _translate("MainWindow", "After"))
        self.comboBoxRecNRB.setItemText(3, _translate("MainWindow", "Both"))
        self.label_17.setText(_translate("MainWindow", "Collect Dark"))
        self.label_21.setText(_translate("MainWindow", "Delay (mm)"))
        self.label_18.setText(_translate("MainWindow", "Collect NRB"))
        self.label_22.setText(_translate("MainWindow", "Delay (mm)"))
        self.label_20.setText(_translate("MainWindow", "Early-Time NRB"))
        self.label_23.setText(_translate("MainWindow", "Delay (mm)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "NRB/Dark Collection"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Fast Axis"))
        self.label_31.setText(_translate("MainWindow", "Axis"))
        self.comboBox_nrb_fast_axis.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_nrb_fast_axis.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_nrb_fast_axis.setItemText(2, _translate("MainWindow", "Z"))
        self.label_32.setText(_translate("MainWindow", "Start (um)"))
        self.label_33.setText(_translate("MainWindow", "Stop (um)"))
        self.label_34.setText(_translate("MainWindow", "Steps"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Slow Axis"))
        self.label_36.setText(_translate("MainWindow", "Axis"))
        self.comboBox_nrb_slow_axis.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_nrb_slow_axis.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_nrb_slow_axis.setItemText(2, _translate("MainWindow", "Z"))
        self.label_37.setText(_translate("MainWindow", "Start (um)"))
        self.label_38.setText(_translate("MainWindow", "Stop (um)"))
        self.label_39.setText(_translate("MainWindow", "Steps"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Fixed Axis"))
        self.label_41.setText(_translate("MainWindow", "Axis"))
        self.comboBox_nrb_fixed_axis.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_nrb_fixed_axis.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_nrb_fixed_axis.setItemText(2, _translate("MainWindow", "Z"))
        self.label_42.setText(_translate("MainWindow", "Position (um)"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "Params"))
        self.pushButtonStartAcq.setText(_translate("MainWindow", "Start"))
        self.pushButtonStopAcq.setText(_translate("MainWindow", "Stop"))
        self.label_30.setText(_translate("MainWindow", "Save?"))
        self.label_26.setText(_translate("MainWindow", "Path and Filename"))
        self.pushButtonBrowseFiles.setText(_translate("MainWindow", "..."))
        self.label_27.setText(_translate("MainWindow", "Dataset Name"))
        self.lineEditDatasetName.setText(_translate("MainWindow", "Experiment"))
        self.label_28.setText(_translate("MainWindow", "Index"))
        self.label_29.setText(_translate("MainWindow", "Group Name"))
        self.lineEditGroupName.setText(_translate("MainWindow", "/BCARSImage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Save"))
        self.plainTextEditMemo.setPlainText(_translate("MainWindow", "Sample:\n"
"\n"
"Notes:\n"
"\n"
"Probe Power = 21 mW\n"
"SC Power = 11 mW"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Memo"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab), _translate("MainWindow", "Image"))
        self.label_13.setText(_translate("MainWindow", "Frequency Index"))
        self.tabWidget_left.setTabText(self.tabWidget_left.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_3), _translate("MainWindow", "Image"))
        self.label_35.setText(_translate("MainWindow", "Frequency Index"))
        self.tabWidget_right.setTabText(self.tabWidget_right.indexOf(self.tab_4), _translate("MainWindow", "Settings"))

