# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt_bcars2_laser_setup.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(505, 323)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Dialog.setFont(font)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonProbeOn = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonProbeOn.setChecked(True)
        self.radioButtonProbeOn.setObjectName("radioButtonProbeOn")
        self.verticalLayout.addWidget(self.radioButtonProbeOn)
        self.radioButtonProbeOff = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonProbeOff.setObjectName("radioButtonProbeOff")
        self.verticalLayout.addWidget(self.radioButtonProbeOff)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.spinBoxProbeSetAmp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxProbeSetAmp.setMaximum(1.0)
        self.spinBoxProbeSetAmp.setSingleStep(0.1)
        self.spinBoxProbeSetAmp.setProperty("value", 1.0)
        self.spinBoxProbeSetAmp.setObjectName("spinBoxProbeSetAmp")
        self.verticalLayout_3.addWidget(self.spinBoxProbeSetAmp)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.spinBoxProbeReadAmp = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxProbeReadAmp.setReadOnly(True)
        self.spinBoxProbeReadAmp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxProbeReadAmp.setMaximum(1.0)
        self.spinBoxProbeReadAmp.setSingleStep(0.1)
        self.spinBoxProbeReadAmp.setProperty("value", 1.0)
        self.spinBoxProbeReadAmp.setObjectName("spinBoxProbeReadAmp")
        self.verticalLayout_2.addWidget(self.spinBoxProbeReadAmp)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.spinBoxProbeSetPrism = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxProbeSetPrism.setDecimals(1)
        self.spinBoxProbeSetPrism.setMinimum(26000.0)
        self.spinBoxProbeSetPrism.setMaximum(33000.0)
        self.spinBoxProbeSetPrism.setSingleStep(100.0)
        self.spinBoxProbeSetPrism.setProperty("value", 28472.0)
        self.spinBoxProbeSetPrism.setObjectName("spinBoxProbeSetPrism")
        self.verticalLayout_6.addWidget(self.spinBoxProbeSetPrism)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.spinBoxProbeReadPrism = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.spinBoxProbeReadPrism.setReadOnly(True)
        self.spinBoxProbeReadPrism.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxProbeReadPrism.setDecimals(1)
        self.spinBoxProbeReadPrism.setMinimum(26000.0)
        self.spinBoxProbeReadPrism.setMaximum(33000.0)
        self.spinBoxProbeReadPrism.setSingleStep(100.0)
        self.spinBoxProbeReadPrism.setProperty("value", 28472.0)
        self.spinBoxProbeReadPrism.setObjectName("spinBoxProbeReadPrism")
        self.verticalLayout_7.addWidget(self.spinBoxProbeReadPrism)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 3)
        self.checkBoxProbeAutoOpti = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxProbeAutoOpti.setObjectName("checkBoxProbeAutoOpti")
        self.gridLayout.addWidget(self.checkBoxProbeAutoOpti, 2, 0, 1, 2)
        self.pushButtonProbeOptiNow = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonProbeOptiNow.setObjectName("pushButtonProbeOptiNow")
        self.gridLayout.addWidget(self.pushButtonProbeOptiNow, 2, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.spinBoxSCSetAmp = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCSetAmp.setMaximum(1.0)
        self.spinBoxSCSetAmp.setSingleStep(0.1)
        self.spinBoxSCSetAmp.setProperty("value", 1.0)
        self.spinBoxSCSetAmp.setObjectName("spinBoxSCSetAmp")
        self.verticalLayout_17.addWidget(self.spinBoxSCSetAmp)
        self.horizontalLayout_5.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_18.addWidget(self.label_15)
        self.spinBoxSCReadAmp = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCReadAmp.setReadOnly(True)
        self.spinBoxSCReadAmp.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSCReadAmp.setMaximum(1.0)
        self.spinBoxSCReadAmp.setSingleStep(0.1)
        self.spinBoxSCReadAmp.setProperty("value", 1.0)
        self.spinBoxSCReadAmp.setObjectName("spinBoxSCReadAmp")
        self.verticalLayout_18.addWidget(self.spinBoxSCReadAmp)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_16, 0, 1, 1, 2)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_19.addWidget(self.label_16)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_20.addWidget(self.label_17)
        self.spinBoxSCSetPre = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCSetPre.setDecimals(1)
        self.spinBoxSCSetPre.setMinimum(26000.0)
        self.spinBoxSCSetPre.setMaximum(33000.0)
        self.spinBoxSCSetPre.setSingleStep(100.0)
        self.spinBoxSCSetPre.setProperty("value", 31600.0)
        self.spinBoxSCSetPre.setObjectName("spinBoxSCSetPre")
        self.verticalLayout_20.addWidget(self.spinBoxSCSetPre)
        self.horizontalLayout_6.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_21.addWidget(self.label_18)
        self.spinBoxSCReadPre = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCReadPre.setReadOnly(True)
        self.spinBoxSCReadPre.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSCReadPre.setDecimals(1)
        self.spinBoxSCReadPre.setMinimum(26000.0)
        self.spinBoxSCReadPre.setMaximum(33000.0)
        self.spinBoxSCReadPre.setSingleStep(100.0)
        self.spinBoxSCReadPre.setProperty("value", 31600.0)
        self.spinBoxSCReadPre.setObjectName("spinBoxSCReadPre")
        self.verticalLayout_21.addWidget(self.spinBoxSCReadPre)
        self.horizontalLayout_6.addLayout(self.verticalLayout_21)
        self.verticalLayout_19.addLayout(self.horizontalLayout_6)
        self.gridLayout_3.addLayout(self.verticalLayout_19, 1, 0, 1, 3)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.radioButtonSCOn = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonSCOn.setChecked(True)
        self.radioButtonSCOn.setObjectName("radioButtonSCOn")
        self.verticalLayout_15.addWidget(self.radioButtonSCOn)
        self.radioButtonSCOff = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonSCOff.setObjectName("radioButtonSCOff")
        self.verticalLayout_15.addWidget(self.radioButtonSCOff)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_22.addWidget(self.label_19)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_23.addWidget(self.label_20)
        self.spinBoxSCSetPost = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCSetPost.setDecimals(1)
        self.spinBoxSCSetPost.setMinimum(10000.0)
        self.spinBoxSCSetPost.setMaximum(18000.0)
        self.spinBoxSCSetPost.setSingleStep(100.0)
        self.spinBoxSCSetPost.setProperty("value", 14000.0)
        self.spinBoxSCSetPost.setObjectName("spinBoxSCSetPost")
        self.verticalLayout_23.addWidget(self.spinBoxSCSetPost)
        self.horizontalLayout_7.addLayout(self.verticalLayout_23)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_24.addWidget(self.label_21)
        self.spinBoxSCReadPost = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.spinBoxSCReadPost.setReadOnly(True)
        self.spinBoxSCReadPost.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinBoxSCReadPost.setDecimals(1)
        self.spinBoxSCReadPost.setMinimum(10000.0)
        self.spinBoxSCReadPost.setMaximum(18000.0)
        self.spinBoxSCReadPost.setSingleStep(100.0)
        self.spinBoxSCReadPost.setProperty("value", 14000.0)
        self.spinBoxSCReadPost.setObjectName("spinBoxSCReadPost")
        self.verticalLayout_24.addWidget(self.spinBoxSCReadPost)
        self.horizontalLayout_7.addLayout(self.verticalLayout_24)
        self.verticalLayout_22.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_22, 2, 0, 1, 3)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Probe"))
        self.radioButtonProbeOn.setText(_translate("Dialog", "ON"))
        self.radioButtonProbeOff.setText(_translate("Dialog", "OFF"))
        self.label.setText(_translate("Dialog", "Amplifer Power Fraction"))
        self.label_2.setText(_translate("Dialog", "Set To"))
        self.label_3.setText(_translate("Dialog", "Current"))
        self.label_4.setText(_translate("Dialog", "Si Prism Position"))
        self.label_5.setText(_translate("Dialog", "Set To"))
        self.label_6.setText(_translate("Dialog", "Current"))
        self.checkBoxProbeAutoOpti.setText(_translate("Dialog", "Auto-Optimize"))
        self.pushButtonProbeOptiNow.setText(_translate("Dialog", "Optimize Now"))
        self.groupBox_2.setTitle(_translate("Dialog", "SC"))
        self.label_13.setText(_translate("Dialog", "Amplifer Power Fraction"))
        self.label_14.setText(_translate("Dialog", "Set To"))
        self.label_15.setText(_translate("Dialog", "Current"))
        self.label_16.setText(_translate("Dialog", "Pre Prism Position"))
        self.label_17.setText(_translate("Dialog", "Set To"))
        self.label_18.setText(_translate("Dialog", "Current"))
        self.radioButtonSCOn.setText(_translate("Dialog", "ON"))
        self.radioButtonSCOff.setText(_translate("Dialog", "OFF"))
        self.label_19.setText(_translate("Dialog", "Post Prism Position"))
        self.label_20.setText(_translate("Dialog", "Set To"))
        self.label_21.setText(_translate("Dialog", "Current"))

